# Small Test Configuration for Quick Testing

# Data Configuration
data:
  input_file: "inputs/training_input_parameter_round18.h5"
  output_file: "inputs/training_output_spectra_round18.h5"
  
  # TARDIS-specific parameters
  v_start_kms: 3000
  v0_kms: 5000
  t0_day: 5
  keep_v_outer: true
  
  # Data splitting
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  
  # Small batch size for testing
  batch_size: 16
  shuffle: true
  num_workers: 0
  random_seed: 42
  
  # Preprocessing
  preprocessing:
    method: "standard"

# Model Configuration - Small network for fast testing
model:
  model_type: "mlp"
  input_dim: null
  output_dim: null
  
  # Small network for quick training
  hidden_dims: [64, 32]
  activation: "relu"
  dropout_rate: 0.1
  use_batch_norm: false
  use_bias: true

# Training Configuration - Fast training for testing
training:
  epochs: 10  # Very few epochs for testing
  task_type: "regression"
  
  # Loss function
  loss:
    type: "mse"
    
  # Optimizer settings
  optimizer:
    type: "adam"
    learning_rate: 0.01  # Higher learning rate for faster convergence
    weight_decay: 0.0
  
  # Simple scheduler
  scheduler:
    type: "step"
    step_size: 5
    gamma: 0.5
  
  # Early stopping disabled for testing
  early_stopping:
    enabled: false
  
  # No gradient clipping
  gradient_clipping: null
  
  # Checkpointing
  checkpointing:
    enabled: true
    checkpoint_dir: "checkpoints/small_test"
    max_checkpoints: 3
  
  # Logging
  logging:
    enabled: true
    log_dir: "logs"
    experiment_name: "small_test"
    use_tensorboard: false  # Disable for faster testing
    log_level: "DEBUG"

# Evaluation Configuration
evaluation:
  metrics:
    - "mse"
    - "rmse"
    - "mae"
  
  plot_training_curves: false
  plot_predictions: false
  results_dir: "results/small_test"

# Experiment Configuration
experiment:
  name: "small_test"
  description: "Small test configuration for debugging and quick testing"
  tags: ["test", "debug", "small"]
  
  random_seed: 42
  deterministic: true
  device: "auto"
  use_amp: false 