# TARDIS Regression Experiment Configuration

# Data Configuration
data:
  input_file: "inputs/training_input_parameter_round18.h5"
  output_file: "inputs/training_output_spectra_round18.h5"
  
  # TARDIS-specific parameters
  v_start_kms: 3000
  v0_kms: 5000
  t0_day: 5
  keep_v_outer: true
  
  # Data splitting
  train_split: 0.8
  val_split: 0.15
  test_split: 0.05
  
  # DataLoader settings
  batch_size: 64
  shuffle: true
  num_workers: 2
  random_seed: 42
  
  # Preprocessing
  preprocessing:
    method: "standard"

# Model Configuration
model:
  model_type: "mlp"
  input_dim: null  # Will be determined from data
  output_dim: null  # Will be determined from data
  
  # Larger network for TARDIS spectral data
  hidden_dims: [1024, 512, 256, 128, 64]
  activation: "relu"
  dropout_rate: 0.2
  use_batch_norm: true
  use_bias: true

# Training Configuration
training:
  epochs: 200
  task_type: "regression"
  
  # Loss function optimized for spectral data
  loss:
    type: "mse"
    
  # Optimizer settings
  optimizer:
    type: "adamw"
    learning_rate: 0.0005
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
  
  # Learning rate scheduler
  scheduler:
    type: "cosine"
    T_max: 200
    eta_min: 1.0e-6
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 1.0e-5
    mode: "min"
    restore_best_weights: true
  
  # Gradient clipping for stability
  gradient_clipping: 1.0
  
  # Checkpointing
  checkpointing:
    enabled: true
    checkpoint_dir: "checkpoints/tardis_regression"
    max_checkpoints: 10
  
  # Logging
  logging:
    enabled: true
    log_dir: "logs"
    experiment_name: "tardis_regression"
    use_tensorboard: true
    log_level: "INFO"

# Evaluation Configuration
evaluation:
  metrics:
    - "mse"
    - "rmse"
    - "mae" 
    - "mape"
    - "r2"
    - "explained_variance"
  
  plot_training_curves: true
  plot_predictions: true
  results_dir: "results/tardis_regression"

# Experiment Configuration
experiment:
  name: "tardis_regression"
  description: "TARDIS supernova spectral regression using MLP"
  tags: ["tardis", "regression", "spectral", "supernova"]
  
  random_seed: 42
  deterministic: true
  device: "auto"
  use_amp: false 